Fixing bugs (src/middlewares/ApiKeyAuth.ts:19:9 - error TS2339: Property 'user' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.)